[package]
name = "uio"
version = "0.1.0"
authors = ["Andreas Wass <wass.andreas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0-alpha.1"